name: Zephyr CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build_and_test:
    name: Build and Test Zephyr Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ./

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends git cmake ninja-build gperf \
            ccache dfu-util device-tree-compiler wget \
            python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
            make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create virtual environment
        run: python -m venv .venv
        shell: bash
        working-directory: ./
        # Update the PATH since every step is run in a new shell.
        env:
          VIRTUAL_ENV: .venv
          PATH: .venv/bin:$PATH

      - name: Cache external directory
        uses: actions/cache@v4
        with:
          path: external
          key: ${{ runner.os }}-zephyr-externals

      - name: Install west
        run: |
          set -e
          source .venv/bin/activate
          pip install west
          west update
          west zephyr-export
          west packages pip --install
          cd external/zephyr
          west sdk install

      - name: Build everything and run tests
        shell: bash
        run: ./build.sh