name: Zephyr CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build_and_test:
    name: Build and Test Zephyr Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ./

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create virtual environment
        run: python -m venv .venv
        shell: bash
        working-directory: ./
        # Update the PATH since every step is run in a new shell.
        env:
          VIRTUAL_ENV: .venv
          PATH: .venv/bin:$PATH

      - name: Cache external directory
        uses: actions/cache@v4
        with:
          path: external
          key: ${{ runner.os }}-zephyr-externals

      - name: Install west
        run: pip install west

      - name: Install west dependencies
        run: west update

      - name: Export CMake
        run: west zephyr-export

      - name: Install additional Python dependencies
        run: west packages pip --install

      - name: Install Zephyr SDK
        run: cd external/zephyr && west sdk install

      # - name: Delete existing west namespaces
      #   shell: bash
      #   run: |
      #     set -e
      #     rm -rf .west

      # - name: Setup Zephyr environment
      #   uses: zephyrproject-rtos/action-zephyr-setup@v1
      #   with:
      #       app-path: src
      #       toolchains: arm-zephyr-eabi
        # app-path defaults to '.', which is correct as west.yml is at the root.
        # toolchains defaults to 'host', which is needed for native_sim.

      # - name: Build tests
      #   shell: bash
      #   run: |
      #     set -e
      #     echo "Current directory: $(pwd)"
      #     ls -la
      #     cd test
      #     echo "Current directory after cd test: $(pwd)"
      #     ls -la
      #     west build -b native_sim

      # - name: Run tests
      #   shell: bash
      #   working-directory: ./test
      #   run: |
      #     set -e
      #     echo "Current directory for running tests: $(pwd)"
      #     ls -la build # To see the structure of the build output
      #     ./build/test/zephyr/zephyr.exe
          
      - name: Build everything and run tests
        shell: bash
        run: ./build.sh